version: "3.8"

services:
  awsproyect-app:
    container_name: awsversion15
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      APP_ENV: "production"  # Lanzamos en modo producción
    restart: always

