version = 0.1

[default.deploy]
stack_name = "Ocaso-App"
region = "eu-north-1"
s3_bucket = "mytemple23"
capabilities = "CAPABILITY_IAM"

[default.deploy.parameters]
stack_name = "Ocaso-app"
resolve_s3 = true
s3_prefix = "Ocaso-app"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
